M48
; DRILL file {KiCad (6.0.7)} date Thu Oct 20 14:14:49 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-20T14:14:49-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X0.1378Y-0.1378
X0.1378Y-1.0433
X2.4213Y-0.1378
X2.4213Y-1.0433
T0
M30
